//-----------------------------------------------------------------------
// <copyright file="PermutationOfStrings.cs" company="Bridgelabz">
//     Company copyright tag.
// </copyright>
//-----------------------------------------------------------------------
namespace FunctionalProgrmas
{
    using System;

    /// <summary>
    /// This class returns permutation of given strings
    /// </summary>
    public class PermutationOfStrings
    {
        /// <summary>
        /// Permutes the specified string.
        /// </summary>
        /// <param name="str">The string.</param>
        /// <param name="l">The l. starting index</param>
        /// <param name="r">The r. last index</param>
        public void Permute(string str, int l, int r)
        {
            ////Here if condition check if first index of str is equal to last index if equal it returns str
            if (l == r)
            {
                Console.WriteLine(str);
            }
            else
            {
                ////iteartion start to swap the string 
                for (int i = l; i <= r; i++)
                {
                    str = this.Swap(str, l, i);
                    ////permute is recursive function
                    this.Permute(str, l + 1, r);
                    ////swap is also recursive func
                    ////the output generated by swap funct is assign to str var
                    str = this.Swap(str, l, i);
                }
            }
        }

        /// <summary>
        /// Swaps the specified a.
        /// </summary>
        /// <param name="a">a.string variable name</param>
        /// <param name="i">The i.start position</param>
        /// <param name="j">The j.second position</param>
        /// <returns>string return type</returns>
        public string Swap(string a, int i, int j)
        {
            char temp;
            char[] charArray = a.ToCharArray();
            temp = charArray[i];
            charArray[i] = charArray[j];
            charArray[j] = temp;
            string s = new string(charArray);
            return s;
        }
    }
}   
